### ISSUE TITLE
v1 framework

### ISSUE THREAD

**Issue by casperdcl** [premAI-io/state-of-open-source-ai#12]
- [x] readme: make readable on GitHub (split bits into a separate `root: index.md`) #13
  + [x] html: use `dirhtml` builder #13
- [x] tests: add `linkcheck`s #13
- [x] html: fix comments integration #13
- [x] html: create remaining chapter stubs #14
- [x] assets: use an external static image host to avoid bloating this repo: [`static.premai.io`](https://github.com/premAI-io/static.premai.io) #17
- [x] credit GH contributors (avatars + links) #17
- [x] html: Bibliography borkes right navbar. Find a fix or report upstream issue? #17
  + https://sourceforge.net/p/docutils/patches/195
  + https://github.com/executablebooks/jupyter-book/pull/2048
- [x] add PR review template & improve contrib guide #17
- [x] fix concurrent builds #17
- [x] fix build instructions #21
- [x] misc minor improvements #23
- [ ] pdf: improve formatting
  + [ ] replace the existing page download (print to pdf) links with proper pdf?
  + [x] improve cover pages #65
  + [x] fix cross-ref linking (e.g. links to chapters are not clickable) #79
  + [x] substitute some unicode chars (e.g. 🟢, 🟡, 🔴, https://tex.stackexchange.com/questions/601479) #79
- [x] html: improve style
  + [x] #42
  + [x] #84 #83 #77 #70 #63
- [x] deploy: pick a new subdomain e.g. `book.premai.io` #24
  + [x] update `repo_url` & references #24
  + [x] plausible #25
- [x] contrib list per-chapter #36
  + https://github.com/casperdcl/git-fame#codeowners
  + https://stackoverflow.com/questions/44888187/get-github-username-through-primary-email
- [x] contrib: Zenodo integration config (`CITATION.cff`/`.zenodo.json`) #41
- [x] open links in new tab #55 <- #50
  + https://github.com/executablebooks/jupyter-book/issues/1070
  + https://stackoverflow.com/questions/25583581/add-open-in-new-tab-links-in-sphinx-restructuredtext
  + https://github.com/sphinx-doc/sphinx/issues/2550
- [x] convert links to references where appropriate (e.g. `arxiv`)
- [x] make repo public
  + [x] enables features like `utteranc.es` comments, CI status badges, dependabot, external PRs, GH contributor lists, Zenodo DOIs, etc.
  + [x] fix Zenodo
  + [x] fix utterances #81
  + [ ] tag `v1`
- [ ] add https://ogp.me metadata
- [ ] add to https://github.com/executablebooks/meta/blob/main/docs/gallery.yml

Follow-up to #11

## v1.1

- [ ] rename repo?
- [ ] fix all `TODO` notes
- [ ] fix all `{{ wip_chapter }}`/`% TODO`/`Work in Progress` notes
- [ ] CI: speed up builds
  + [x] maybe parallel `linkcheck` + `html` + `pdf` #69
  + [ ] smaller `pdf` docker container? (easier since https://github.com/xu-cheng/latex-action/releases/tag/3.0.0) (alternatively, use different/quicker `pdf` action?)
  + [ ] add minimal `pdf` LaTeX to DevContainer (and use https://github.com/devcontainers/ci)?
